export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const LOAD_PHOTOS_SUCCESS = "LOAD_PHOTOS_SUCCESS";
export const FILTER_BY_ALBUM = "FILTER_BY_ALBUM";
export const SELECT_FAVOURITE = "SELECT_FAVOURITE";
export const UNSELECT_FAVOURITE = "UNSELECT_FAVOURITE";
export const VIEW_FAVOURITES = "VIEW_FAVOURITES";
